# Generated by Django 5.1.4 on 2025-04-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='user',
        ),
    ]
