# Generated by Django 5.1.4 on 2025-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_title_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forum.ticket'),
        ),
    ]
