# Generated by Django 5.1.4 on 2025-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_profile_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tickets',
        ),
        migrations.AddField(
            model_name='profile',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='forum.ticket'),
        ),
    ]
