# Generated by Django 5.1.4 on 2025-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_profile_tickets_profile_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='forum.ticket'),
        ),
    ]
