# Generated by Django 5.1.4 on 2025-05-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ticket')),
            ],
        ),
    ]
